[package]
name = "derive-tests"
version = "0.1.1"
authors = ["Jacob Halsey <jacob@jhalsey.com>"]
edition = "2018"

[dev-dependencies]
actix-easy-multipart = { path = "../actix-easy-multipart", features = ["derive"] }
mime = "0.3.16"
tempfile = "~3.1.0"
